version: 2
jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
      - run: date

workflows:
  version: 2
  daily:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
