version: 2
jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
      - run: git --version
      - run: ssh git@github.com || true
      - run: |
          cat README.md
          date >> README.md
          cat README.md
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: |
          git commit -am 'update from Circle CI!'
          git push
