version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: os-release
          command: cat /etc/os-release
