version: 2
jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
      - run: git --version
      - run: ssh git@github.com || true
      - run: date >> README.md
      - run: git commit -am 'update from Circle CI!' || true
      - run: git push
