version: 2
jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
      - run: git --version
      - run: ssh git@github.com || true
      - run: |
          cat README.md
          date >> README.md
          cat README.md
